
name: publish-prod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@cbvcode'

      - name: Install dependencies
        run: yarn install

      - name: Check for build script
        id: check_build
        run: |
          if grep -q '"build":' package.json; then
            echo "::set-output name=has_build::true"
          else
            echo "::set-output name=has_build::false"
          fi

      - name: Build
        if: steps.check_build.outputs.has_build == 'true'
        run: yarn build

      - name: Setup for publishing
        run: |
          echo '@cbvcode:registry=https://npm.pkg.github.com/ 
          //npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_GITHUB_TOKEN }}' > .npmrc

      - name: Publish to GitHub Packages
        run: yarn publish
